sonar.projectKey=todo-api
sonar.projectName=todo-api
sonar.projectVersion=1.0

# Código fuente a analizar
sonar.sources=src
sonar.tests=test
sonar.exclusions=node_modules/**,coverage/**

sonar.sourceEncoding=UTF-8
